<img src='images/a.webp'>

<img src='images/filter.gif'>

<img src='images/filter2.gif'>

<img src='images/filter3.gif'>

<img src='images/filter4.gif'>

## 원이미지와 kernel(filter)를 convolution 하려는데 가상에는 데이터가 부족해서 0을 추가해야 하므로 이것을 zero padding 이라함

0패딩 말고 인접한 데이트를 padding 할 수 있음

<img src='images/convolution.png'>

<img src='images/convolution.gif'>

<img src='images/equation.png'>

<img src='images/equation2.png'>

In [1]:
import numpy as np

In [2]:
A=np.array([[-1,1,0,1,0],
           [-1,3,1,2,5],
           [-1,2,5,6,7],
           [8,-1,1,0,1],
           [-1,0,0,1,0]
          ])

B=np.array([[-1,0,1],
    [0,1,0],
    [0,0,1]
   ])

AA=np.pad(A, ((1,1),(1,1)), constant_values=0)
AA

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0, -1,  3,  1,  2,  5,  0],
       [ 0, -1,  2,  5,  6,  7,  0],
       [ 0,  8, -1,  1,  0,  1,  0],
       [ 0, -1,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [3]:
a=np.array([[0,0,0],
 [ 1, 0,  1],
 [ 3, 1,  2]])
b=np.array([[-1,0,1],
    [0,1,0],
    [0,0,1]
   ])
np.multiply(a,b).sum()

2

In [4]:
Convolution=[]

a_row=len(AA[0])
a_col=len(AA)
b_row=len(B[0])
b_col=len(B)

print(a_row,a_col)
print(b_row,b_col)


for i in range(a_row-b_row+1):
    print(i)
    new_list=[]
    for j in range(a_col-b_col+1):
#         print(AA[i:i+b_col,j:j+b_col])
        new_list.append((np.sum(np.multiply(AA[i:i+b_col,j:j+b_col],B))))
    Convolution.append(new_list)
np.array(Convolution)

7 7
3 3
0
1
2
3
4


array([[ 2,  2,  2,  6,  0],
       [ 2,  9,  7,  9,  4],
       [ 1,  5,  4, 11,  5],
       [10,  5,  6,  2, -5],
       [-2, -7,  1,  1,  0]])

In [5]:
image=[[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0, -1,  3,  1,  2,  5,  0],
       [ 0, -1,  2,  5,  6,  7,  0],
       [ 0,  8, -1,  1,  0,  1,  0],
       [ 0, -1,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]
      ]
filter1=[[-1,0,1],
    [0,1,0],
    [0,1,1]
   ]
list1=[image[0][0:3],image[1][0:3],image[2][0:3]]
np.dot(list1,filter1)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 2, 3]])

In [6]:
a,b=np.array([[1,2],[1,2]]),np.array([[1,2],[1,2]])

In [7]:
a@b

array([[3, 6],
       [3, 6]])

In [8]:
image=np.array([[-1,1,0,1,0],
           [-1,3,1,2,5],
           [-1,2,5,6,7],
           [8,-1,1,0,1],
           [-1,0,0,1,0]
          ])

filtered=np.array([[-1,0,1],
    [0,1,0],
    [0,0,1]
   ])

In [9]:
padded_image = []
padded_zero = np.array([ 0 for i in range(5)]) #5개
padded_image.append(padded_zero) #첫번째 행에 추가
for i in image:
    padded_image.append(i) #image를 다추가
padded_image.append(padded_zero) #마지막행에 0 추가
transposed_first = np.array(padded_image)
padded_zero = np.array([ 0 for i in range(7)]) #7개를 0으로 만든다
copyed = np.array([ padded_zero , *transposed_first.T, padded_zero])
padded_image = copyed.T
padded_image

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  1,  0,  1,  0,  0],
       [ 0, -1,  3,  1,  2,  5,  0],
       [ 0, -1,  2,  5,  6,  7,  0],
       [ 0,  8, -1,  1,  0,  1,  0],
       [ 0, -1,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [10]:
convolved=[]
for j in range(5):
    convolved.append([sum(sum(np.multiply(padded_image[j:j+3,i:i+3],filtered))) for i in range(5)])
convolved

[[2, 2, 2, 6, 0],
 [2, 9, 7, 9, 4],
 [1, 5, 4, 11, 5],
 [10, 5, 6, 2, -5],
 [-2, -7, 1, 1, 0]]

<img src="images/공식.jpg">

<img src="images/filter6.jpg">

<img src="images/filter7.jpg">

<a href='https://velog.io/@se0yeon00/%EC%98%81%EC%83%81%EC%8B%A0%ED%98%B8%EC%B2%98%EB%A6%AC'> 영상 신호 처리 필터</a>

<a href='https://programmingfbf7290.tistory.com/entry/%EC%A3%BC%ED%8C%8C%EC%88%98-%EC%98%81%EC%97%AD-%EC%98%81%EC%83%81-%ED%95%84%ED%84%B0%EA%B0%80%EC%9A%B0%EC%8B%9C%EC%95%88-%EC%A3%BC%ED%8C%8C%EC%88%98-%ED%95%84%ED%84%B0'>영상 신호 처리 가우시안</a>

<a href='https://junstar92.tistory.com/405'>영상 신호 처리 가우시안</a>

In [1]:
import cv2
import numpy as np

In [2]:
def preprocessing(image):
    image = cv2.imread(image)
    image = cv2.cvtColor(src=image,code=cv2.COLOR_BGR2GRAY)
    return image

In [13]:
def convolve2D(image ,kernel ,padding =0, strides=1):
    #kernel = filter , stride=>몇칸씩 이동하면서 convolution할지 결정
    kernel =np.flipud(np.fliplr(kernel)) #left right(수평뒤집기), up ->down(수직뒤집기)
    #이미지와 kernel의  shape을 구함 
    xKernelShape = kernel.shape[0]
    yKernelShape = kernel.shape[1]
    xImageShape = image.shape[0]
    yImageShape =image.shape[1]
    #각각의 출력 차원을 크기 공식을 적용하여 구할수 있음 
    xOutput =int(((xImageShape- xKernelShape +2*padding)/strides) +1 ) #위의 공식 
    yOutput = int(((yImageShape- yKernelShape +2*padding)/strides) +1 )
#     print(xOutput,yOutput)
    output = np.zeros((xOutput, yOutput))
    if padding !=0:
        imagePadded =np.zeros((image.shape[0] + padding*2,  image.shape[1] +padding*2))
        # padded 이미지의 내부는 실제 이미지로 대체함 (slicing 사용하여)
        imagePadded[int(padding):int(-1*padding) , int(padding):int(-1*padding) ] =image
    else: #padding이 없다면 
        imagePadded=image
    for y in range(image.shape[1]): # 반복하면서 이미지의 크기보다  커널의 크기가 작으면 종료 
        if y>image.shape[1] -yKernelShape: break
        if y% strides==0: #특정 stride 만큼 내려갈때만 convolution 함
            for x in range(image.shape[0]):
                #  커널의 경계를 벗어나면  다음 행으로 이동 
                if x >image.shape[0] - xKernelShape: break
                try:
                    if x%strides ==0: #x의 값이  strides의 배수가 될때만 
                        #특정 stride로 이동할때만 convolution 함
                        output[x,y] =(kernel *imagePadded[x:x+xKernelShape, y:y+yKernelShape]).sum()
                except:
                    break
    return output

In [4]:
kernel_blur3= np.array([[1/16, 1/8, 1/16],
                        [1/8, 1/4, 1/8],
                        [1/16, 1/8, 1/16]]) #가우시안

In [5]:
gaussian_filter_5x5 = np.array([
    [1/256, 4/256, 6/256, 4/256, 1/256],
    [4/256, 16/256, 24/256, 16/256, 4/256],
    [6/256, 24/256, 36/256, 24/256, 6/256],
    [4/256, 16/256, 24/256, 16/256, 4/256],
    [1/256, 4/256, 6/256, 4/256, 1/256]
])

In [6]:
kernel_3x= np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]) 

In [7]:
kernel_5x= np.array([[-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1],[-1,-1,24,-1,-1],
                 [-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1]]) 

In [8]:
kernel_7x= np.array([[-1,-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1,-1],
                     [-1,-1,-1,48,-1,-1,-1],
                 [-1,-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1,-1],[-1,-1,-1,-1,-1,-1,-1]]) 

In [9]:
kernel_1= np.array([[1,2,1],
                    [0,0,0],
                    [-1,-2,-1]])
kernel_2= np.array([[1,0,-1],
                    [2,0,-2],
                    [1,0,-1]]) 

In [10]:
list_kernel = [kernel_3x,kernel_5x,kernel_7x,kernel_blur3,gaussian_filter_5x5,kernel_1,kernel_2]

In [14]:
for idx,kernel in enumerate(list_kernel):
    image=preprocessing('images/lenna.png')
    print(image.shape)
    output=convolve2D(image,kernel,padding=2)
#     cv2.imwrite('2Dconvolvedx_'+str(idx)+'.jpg',output)

(512, 512)
3
514 514
(512, 512)
5
512 512
(512, 512)
7
510 510
(512, 512)
3
514 514
(512, 512)
5
512 512
(512, 512)
3
514 514
(512, 512)
3
514 514


In [78]:
for i in range(len(list_kernel)):
    image=preprocessing('images/vertical.jpg')
    print(image.shape)
    output=convolve2D(image,list_kernel[i],padding=2)
    cv2.imwrite('2Dconvolvedx_'+str(i)+'.jpg',output)

(600, 1000)
(600, 1000)
(600, 1000)
(600, 1000)
(600, 1000)
(600, 1000)
(600, 1000)
