In [1]:
import numpy as np
import cv2


def camera_in():
    cap = cv2.VideoCapture(0)

    if not cap.isOpened():
        print("Camera open failed!")
        return

    print('Frame width:', int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
    print('Frame height:', int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        inversed = ~frame

        cv2.imshow('frame', frame)
        cv2.imshow('inversed', inversed)

        if cv2.waitKey(10) == 27:
            break

    cv2.destroyAllWindows()


def video_in():
    cap = cv2.VideoCapture('images/stopwatch.avi')

    if not cap.isOpened():
        print("Video open failed!")
        return

    print('Frame width:', int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)))
    print('Frame height:', int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
    print('Frame count:', int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))

    fps = cap.get(cv2.CAP_PROP_FPS)
    print('FPS:', fps)

    delay = round(1000 / fps)

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        inversed = ~frame

        cv2.imshow('frame', frame)
        cv2.imshow('inversed', inversed)

        if cv2.waitKey(delay) == 27:
            break

    cv2.destroyAllWindows()


def camera_in_video_out():
    cap = cv2.VideoCapture(0)

    if not cap.isOpened():
        print("Camera open failed!")
        return

    w = round(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = round(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    fourcc = cv2.VideoWriter_fourcc(*'DIVX') # *'DIVX' == 'D', 'I', 'V', 'X'
    delay = round(1000 / fps)

    outputVideo = cv2.VideoWriter('output.avi', fourcc, fps, (w, h))

    if not outputVideo.isOpened():
        print('File open failed!')
        return

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        inversed = ~frame

        outputVideo.write(inversed)

        cv2.imshow('frame', frame)
        cv2.imshow('inversed', inversed)

        if cv2.waitKey(delay) == 27:
            break

    cv2.destroyAllWindows()


if __name__ == '__main__':
    camera_in()
    video_in()
    camera_in_video_out()


Camera open failed!
Frame width: 640
Frame height: 480
Frame count: 378
FPS: 30.0
Camera open failed!


In [2]:
import cv2
import numpy as np
fourcc = cv2.VideoWriter_fourcc(*'DIVX')
writer = cv2.VideoWriter('images/test1.avi',fourcc,25,(640,480),False)
for i in range(100):
    x=np.random.randint(255,size=(460,640)).astype('uint8')
    x=np.repeat(x,3,axis=1)
#     x=x.reshape(480,640,3)
    writer.write(x)

In [3]:
!pip install imutils

In [5]:
from __future__ import print_function
import numpy as np
import imutils
import time
import cv2


output = 'images/example.avi'
video = 'images/stopwatch.avi' #읽어드릴 파일
fps = 33
codec ='MJPG'

vs = cv2.VideoCapture(video)
time.sleep(2.0)
#  FourCC, video writer, frame 차원, zeros배열로 초기화
fourcc = cv2.VideoWriter_fourcc(*codec) #저장하기 위한 객체 생성
writer = None
(h, w) = (None, None) #세로(height),가로(width)
zeros = None
cnt=0
while True:
    ret, frame = vs.read() #입력 비디오 파일로부터 한 프레임 이미지씩 읽어드린다
    cnt+=1
    if cnt%33==0:
            print(cnt, frame.shape)
    else:
        print(ret)
        

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
33 (480, 640, 3)
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
66 (480, 640, 3)
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
99 (480, 640, 3)
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
132 (480, 640, 3)
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
165 (480, 640, 3)
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
Tru

AttributeError: 'NoneType' object has no attribute 'shape'

In [6]:
from __future__ import print_function
import numpy as np
import imutils
import time
import cv2

output = 'images/example.avi'
video = 'images/stopwatch.avi' #읽어드릴 파일
fps = 33
codec ='MJPG'

vs = cv2.VideoCapture(video)
time.sleep(2.0)
#  FourCC, video writer, frame 차원, zeros배열로 초기화
fourcc = cv2.VideoWriter_fourcc(*codec) #저장하기 위한 객체 생성
writer = None
(h, w) = (None, None) #세로(height),가로(width)
zeros = None
cnt=0
    
while True:
    ret, frame = vs.read() #입력 비디오 파일로부터 한 프레임 이미지씩 읽어드린다
    if ret==True:
        frame = imutils.resize(frame, width=300) #크기를 재조정
        print(frame.shape)
    else:
        break
    if writer is None: #check writer 없는지 확인

        (h, w) = frame.shape[:2] #흑백으로 만들겠다(225,300,3)=>225 ,300
        writer = cv2.VideoWriter(output, fourcc, fps,
            (w * 2, h * 2), True)
        zeros = np.zeros((h, w), dtype="uint8")

    #승주꺼
    (B, G, R) = np.zeros(frame.shape),np.zeros(frame.shape),np.zeros(frame.shape) #B,G,R(Channel)을 분리해서 담
    for x,i in enumerate(frame):
        for y,j in enumerate(i):
            B[x][y][0],G[x][y][1],R[x][y][2] = j
    
    # opencv (BRG) => 일반 포맷으로 저장하기 위해 rgb로 변환해서 저장
    # numpy 파이썬 가지고 cv2의 split과 merge 기능 구현
    
    print(B[:20],G[:20],R[:20])
    
    output = np.zeros((h * 2, w * 2, 3), dtype="uint8")
    output[0:h, 0:w] = frame
    output[0:h, w:w * 2] = R
    output[h:h * 2, w:w * 2] = G
    output[h:h * 2, 0:w] = B

    writer.write(output)

    cv2.imshow("Frame", frame)
    cv2.imshow("Output", output)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("q") or key == ord("Q") :
        break

print("[INFO] cleaning up...")
cv2.destroyAllWindows()
vs.release()
writer.release()

(225, 300, 3)
[[[ 28.   0.   0.]
  [ 29.   0.   0.]
  [ 34.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]

 [[ 27.   0.   0.]
  [ 27.   0.   0.]
  [ 32.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]

 [[ 30.   0.   0.]
  [ 29.   0.   0.]
  [ 36.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]

 ...

 [[ 22.   0.   0.]
  [ 22.   0.   0.]
  [ 25.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]

 [[ 27.   0.   0.]
  [ 27.   0.   0.]
  [ 32.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]

 [[ 36.   0.   0.]
  [ 39.   0.   0.]
  [ 42.   0.   0.]
  ...
  [248.   0.   0.]
  [248.   0.   0.]
  [248.   0.   0.]]] [[[  0.  29.   0.]
  [  0.  28.   0.]
  [  0.  33.   0.]
  ...
  [  0. 251.   0.]
  [  0. 251.   0.]
  [  0. 251.   0.]]

 [[  0.  29.   0.]
  [  0.  27.   0.]
  [  0.  32.   0.]
  ...
  [  0. 251.   0.]
  [  0. 251.   0.]
  [  0. 251.   0.]]

 [[ 

(225, 300, 3)
[[[ 26.   0.   0.]
  [ 23.   0.   0.]
  [ 28.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 21.   0.   0.]
  [ 26.   0.   0.]
  [ 34.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 27.   0.   0.]
  [ 32.   0.   0.]
  [ 39.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 ...

 [[ 24.   0.   0.]
  [ 30.   0.   0.]
  [ 34.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 32.   0.   0.]
  [ 29.   0.   0.]
  [ 31.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 38.   0.   0.]
  [ 34.   0.   0.]
  [ 36.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]] [[[  0.  30.   0.]
  [  0.  31.   0.]
  [  0.  38.   0.]
  ...
  [  0. 252.   0.]
  [  0. 252.   0.]
  [  0. 252.   0.]]

 [[  0.  33.   0.]
  [  0.  32.   0.]
  [  0.  35.   0.]
  ...
  [  0. 252.   0.]
  [  0. 252.   0.]
  [  0. 252.   0.]]

 [[ 

(225, 300, 3)
[[[ 29.   0.   0.]
  [ 23.   0.   0.]
  [ 26.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 28.   0.   0.]
  [ 29.   0.   0.]
  [ 34.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 25.   0.   0.]
  [ 27.   0.   0.]
  [ 33.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 ...

 [[ 26.   0.   0.]
  [ 29.   0.   0.]
  [ 39.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 26.   0.   0.]
  [ 26.   0.   0.]
  [ 34.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]

 [[ 42.   0.   0.]
  [ 38.   0.   0.]
  [ 35.   0.   0.]
  ...
  [249.   0.   0.]
  [249.   0.   0.]
  [249.   0.   0.]]] [[[  0.  33.   0.]
  [  0.  32.   0.]
  [  0.  37.   0.]
  ...
  [  0. 252.   0.]
  [  0. 252.   0.]
  [  0. 252.   0.]]

 [[  0.  30.   0.]
  [  0.  34.   0.]
  [  0.  36.   0.]
  ...
  [  0. 252.   0.]
  [  0. 252.   0.]
  [  0. 252.   0.]]

 [[ 

In [13]:
from __future__ import print_function
import numpy as np
import imutils
import time
import cv2

output = 'images/example1.avi'
video = 'images/stopwatch.avi' #읽어드릴 파일
fps = 33
codec ='MJPG'

vs = cv2.VideoCapture(video)
time.sleep(2.0)
#  FourCC, video writer, frame 차원, zeros배열로 초기화
fourcc = cv2.VideoWriter_fourcc(*codec) #저장하기 위한 객체 생성
writer = None
(h, w) = (None, None) #세로(height),가로(width)
zeros = None
cnt=0
    
while True:
    ret, frame = vs.read() #입력 비디오 파일로부터 한 프레임 이미지씩 읽어드린다
    if ret==True:
        frame = imutils.resize(frame, width=300) #크기를 재조정
        print(frame.shape)
    else:
        break
    if writer is None: #check writer 없는지 확인

        (h, w) = frame.shape[:2] #흑백으로 만들겠다(225,300,3)=>225 ,300
        writer = cv2.VideoWriter(output, fourcc, fps,
            (w * 2, h * 2), True)
        zeros = np.zeros((h, w), dtype="uint8")

    b,g,r = frame[:,:,0],frame[:,:,1],frame[:,:,2] #B,G,R(Channel)을 분리
    R=np.zeros(frame.shape) #복사할 채널을 0으로 채우고
    R[:,:,2] = r #각 채널에 복사
    G=np.zeros(frame.shape)
    G[:,:,1] = g
    B=np.zeros(frame.shape) 
    B[:,:,0] = b
    
    # opencv (BRG) => 일반 포맷으로 저장하기 위해 rgb로 변환해서 저장
    # numpy 파이썬 가지고 cv2의 split과 merge 기능 구현
    
#     print(B[:20],G[:20],R[:20])
    
    output = np.zeros((h * 2, w * 2, 3), dtype="uint8")
    output[0:h, 0:w] = frame
    output[0:h, w:w * 2] = R
    output[h:h * 2, w:w * 2] = G
    output[h:h * 2, 0:w] = B

    writer.write(output)

    cv2.imshow("Frame", frame)
    cv2.imshow("Output", output)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("q") or key == ord("Q") :
        break

print("[INFO] cleaning up...")
cv2.destroyAllWindows()
vs.release()
writer.release()

(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 300, 3)
(225, 

In [7]:
from __future__ import print_function
import numpy as np
import imutils
import time
import cv2




output = 'images/example.avi'
video = 'images/stopwatch.avi' #읽어드릴 파일
fps = 33
codec ='MJPG'


vs = cv2.VideoCapture(video)
time.sleep(2.0)
#  FourCC, video writer, frame 차원, zeros배열로 초기화
fourcc = cv2.VideoWriter_fourcc(*codec) #저장하기 위한 객체 생성
writer = None
(h, w) = (None, None) #세로(height),가로(width)
zeros = None
cnt=0
    
while True:
    cnt+=1
    if cnt%33==0:
            ret, frame = vs.read() #입력 비디오 파일로부터 한 프레임 이미지씩 읽어드린다
            print(cnt, frame.shape)
    if ret==True:
        frame = imutils.resize(frame, width=300) #크기를 재조정
    # check if the writer is None
    else:
        break
    if writer is None:

        (h, w) = frame.shape[:2]
        writer = cv2.VideoWriter(output, fourcc, fps,
            (w * 2, h * 2), True)
        zeros = np.zeros((h, w), dtype="uint8")

    (B, G, R) = cv2.split(frame)
    A=cv2.merge([B*0.5,G*0.3,R*0.2])
    R = cv2.merge([zeros, zeros, R])
    G = cv2.merge([zeros, G, zeros])
    B = cv2.merge([B, zeros, zeros])

#     print(B[:20],G[:20],R[:20])
    output = np.zeros((h * 2, w * 2, 3), dtype="uint8")
    output[0:h, 0:w] = A
    output[0:h, w:w * 2] = R
    output[h:h * 2, w:w * 2] = G
    output[h:h * 2, 0:w] = B

    writer.write(output)

    cv2.imshow("Frame", frame)
    cv2.imshow("Output", output)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("q") or key == ord("Q") :
        break

print("[INFO] cleaning up...")
cv2.destroyAllWindows()
vs.release()
writer.release()

33 (480, 640, 3)
66 (480, 640, 3)
99 (480, 640, 3)
[INFO] cleaning up...


In [8]:
output=np.zeros((400,600,3),dtype="uint8")
h=300
w=200
output[:w,:h,0]=int(255*0.5)
output[:w,:h,1]=int(255*0.3)
output[:w,:h,2]=int(255*0.2)
output[:w,h:,0]=255
output[w:,h:,1]=255
output[w:,:h,2]=255

while True:
    cv2.imshow("Frame",output)
    key = cv2.waitKey(1)&0xFF
    if key == ord("q") or key == ord("Q"):
        break
cv2.destroyAllWindows()

In [ ]:
x = np.zeros((400,800,3))
x[190:210,390:410,2]=(255)
cv2.imshow('img',x)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import time
start_time=time.time()
x = np.zeros((400,800,3))
x[:100,:100,0]=255
cv2.imshow('img',x)
cv2.waitKey(1)
x[200:210,390:400,0]=30
cv2.imshow('img',x)
cv2.destroyAllWindows()

In [ ]:
TIMER=int(20)
cap = cv2.VideoCapture('images/stopwatch.avi')
while True:
    ret,img = cap.read()
    cv2.imshow('a',img)
    k=cv2.waitKey(125)
    if k==ord('q'):
        prev=time.time()
        while TIMER>=0:
            ret,img = cap.read()
            font = cv2.FONT_HERSHEY_SIMPLEX
            cv2.putText(img,str(TIMER),(200,250),FONT,7(0,255,255),4,cv2.LINE_AA)
            cv2.imshow('a',img)
            cv2.waitKey(125)
            cur = time.time()
            if cur-prev>=1:
                prev=cur
                TIMER=TIMER-1
            else:
                ret,img = cap.read()
                cv2.imshow('a',img)
                cv2.waitKey(2000)
                cv2.imwrite('images/camera.jpg',img)
    elif k==27:break
cap.release()
cv2.destroyAllWindows()

        