In [1]:
## numpy 고성능 수치계산을 위해 과학자들이 만들어놓음
import numpy as np 
#import numpy 만 해도 되지만, 이를 코드에서 보다 편하게 사용하기 위해 as np 를 붙임으로써 np라는 이름으로 numpy를 사용  

In [2]:
x = np.array([3,4,2])
x

array([3, 4, 2])

In [3]:
np.shape((x*2)) #shape 배열 형태 보여쥼?

(3,)

In [4]:
np.shape((x*2).T) #T메서드(transpose) 행과 열을 바꾸쥼

(3,)

In [5]:
x2=np.array([[1,2,3,4],[4,5,6,7]]) #2행 4열
np.shape(x2)

(2, 4)

In [6]:
y2=np.array([[1,2,3,4],[4,5,6,7]]).T #4행 2열
np.shape(y2)

(4, 2)

In [7]:
# np.dot(x2,x2)
np.dot(x2,y2) #dot 내적

array([[ 30,  60],
       [ 60, 126]])

In [8]:
np.shape(np.dot(x2,y2) )

(2, 2)

$$ x_2= \begin{bmatrix}
 1& 2&  3& 4 \\
 4&  5& 6& 7  
\end{bmatrix} $$

2행 4열과 2행을 4열의 행렬곱은 불가능 <br>
(2x4)행과 (2x4) 행력의 곱은 불가능하고<br>
곱하려는 앞의 행렬의 열(4)과 곱하려는 행렬의 행이 같아야 계산할수 있다.<br>
만약 (2x4),(4x3)을 곱하면 결과의 형태는 (2x3)열의 형태가 된다.<br>

In [9]:
A1=np.array([2,3])
B1=np.array([3,4])

In [10]:
np.dot(A1,B1)

18

In [11]:
A1[0]*B1[0]+A1[1]*B1[1]

18

## 벡터의 크기
$$ \overrightarrow{a} = (a_1,a_2,a_3,....a_{n_1},a_n) $$
$$ \sqrt{a_1^2+a_2^2+\cdot \cdot\cdot\cdot + a_{n-1}^2+a_{n}^2} $$
$$ \sqrt{\sum_{i=0}^na_i^2} $$

In [12]:
#|A1| , A1 벡터의 크기
np.sqrt(A1[0]*A1[0] + A1[1]*A1[1]) #sqrt 루트

3.605551275463989

In [13]:
#|B1| , B1 벡터의 크기
np.sqrt(B1[0]*B1[0] + B1[1]*B1[1]) #sqrt 루트

5.0

In [14]:
#반복문으로 
a1 = 0
for i in A1:
    a1 += i*i
np.sqrt(a1)

3.605551275463989

In [15]:
b1 = 0
for i in B1:
    b1 += i*i
np.sqrt(b1)

5.0

In [16]:
np.sqrt(sum([i**2 for i in A1]))

3.605551275463989

## 내적의 정의 
$$ \overrightarrow{a}\cdot \overrightarrow{b}  = 
    (a_1\cdot{b_1}+ a_2\cdot{b_2}+ a_3\cdot{b_3} +...+a_{n-1}\cdot{b_{n-1}}+ a_n\cdot{b_{n}} ) 
$$
$$ |a|\cdot|b|cos\theta $$
$$  cos\theta  = \frac{\overrightarrow{a}\cdot \overrightarrow{b}}{|a|\cdot|b|} $$
$$ x= cos\theta \rightarrow \theta = cos^{-1}{x} $$

In [17]:
#zip 두개를 묶어줌
for i in zip([1,2,3],[4,5,6]):
    print(i)

(1, 4)
(2, 5)
(3, 6)


In [18]:
#문제 반복문으로 내적하는 코드 만들기 zip활용
# np.dot(A1,B1)이랑 값 같음
result_dot=0
for i in zip(A1,B1): #A1=[2,3] B1=[3,4] , zip(A1,B1) => (2,3) (3,4)로 묶어줌
    result_dot+= i[0]*i[1]
result_dot

18

In [34]:
def dot(x1,y1): #내적 함수 정의하기  
    result_dot=0
    for i in zip(x1,y1): #A1=[2,3] B1=[3,4] , zip(A1,B1) => (2,3) (3,4)로 묶어줌
        result_dot+= i[0]*i[1]
    return result_dot

In [35]:
def abs_vector(x):
    a1_abs=0
    for i in x:
        a1_abs+=i*i
    return np.sqrt(a1_abs)

In [36]:
A1=np.array([33,22])
B1=np.array([-2,3])

In [37]:
cos_theta1 = dot(A1,B1)/(abs_vector(A1)*abs_vector(B1))
cos_theta1

0.0

In [38]:
cos_theta2 = dot(A1,A1)/(abs_vector(A1)*abs_vector(A1))
cos_theta2

1.0000000000000002

In [24]:
abs_vector(A1)

39.66106403010388

In [25]:
abs_vector(B1)

3.605551275463989

In [26]:
c1=np.array([2,3,7])
d1=np.array([3,4,11])

In [27]:
abs_vector(c1)

7.874007874011811

In [28]:
abs_vector(d1)

12.083045973594572

$$ 3x+ 2y+4z = 11 $$
$$ 2x+ 3y-z = 21 $$ 
$$ -x+ 4y+3z = 7 $$ 
$$  A =  \begin{bmatrix}
3 & 2 & 4 \\
 2& 3 &-1  \\
 -1& 4 & 3  
\end{bmatrix}  $$ 
$$   x =  \begin{bmatrix}
 x\\
 y\\
z
\end{bmatrix} $$

$$   b =  \begin{bmatrix}
 11\\
 21\\
7
\end{bmatrix} $$

$$ I = \begin{bmatrix}
 1& 0 & 0\\
 0& 1 & 0\\
 0& 0 & 1 
\end{bmatrix} $$
대각 성분이 1이고 나머지는 0인 행렬을 단위행렬(identuty)이라 함
어떤 행렬에 I를 곱하면 자기 자신 <br>
곱셈에 대한 항등원은 1이다.
그리고 역원은 어떤 숫자에 뭐를 곱했더니 곱셈에 대한 항등원 1이 나오는가<br>
행렬에서 곱셈의 항등원이 i이고
그리고 곱세의 항등원이 되기 위한 행렬에 어떤 행렬을 곱했더니 행렬의 항등원인 단위 행렬이 나오는가?
$$ A \cdot B = B \cdot A = I$$
결국 $ B = A^{-1} $가 된다.
$$ 4X = 1 \rightarrow x= \frac{1}{4} = 4^{-1}
$$ A^{-1} $를 A의 역행렬이라한다.


In [46]:
I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])
np.shape(I)

(3, 3)

In [42]:
np.dot(A,I)

array([[ 3,  2,  4],
       [ 2,  3, -1],
       [-1,  4,  3]])

In [1]:
A = np.array([[3,2,4],
              [2,3,-1],
              [-1,4,3]])
# np.shape(A)
# A
# np.linalg.inv(A)


NameError: name 'np' is not defined

In [2]:
c1= A.T[0]
c2= A.T[1]
c3= A.T[2]
c1
c2
c3

NameError: name 'A' is not defined

In [49]:
b=np.array([11,21,7])

In [76]:
x=np.dot(np.linalg.inv(A),b) #np.linalg.inv() 역행렬 가져오는 메서드,  np.linalg.inv(A) A의 역행렬, A^-1 X b
# x
x[0]*c1 + x[1]*c2 + x[2]*c3
# 역행렬은 행렬에 곱해서 단위 행렬을 만들수있는 값이구나............
# 행렬에 단위행렬 곱하면 똑같은값 나옴

array([11., 21.,  7.])