In [1]:
!pip install opencv-python

In [2]:
import sys

In [3]:
import cv2

In [4]:
cv2.__version__

'4.8.0'

In [5]:
img = cv2.imread('images/lenna.bmp')
print(img.shape)
img=img[:, :int(img.shape[1]/2)]
if img is None: #이미지 없으면 None임
    print("이미지 로딩 실패")
    sys.exit() #종료
cv2.namedWindow('image')
cv2.imshow('image',img)
cv2.waitKey()
cv2.destroyAllWindows()

(512, 512, 3)


In [6]:
import numpy as np

In [7]:
def funct1():
    img1 = cv2.imread('images/cat.bmp',cv2.IMREAD_GRAYSCALE)
    if img1 is None:
        print("이미지 로딩 실패")
        return
    print('type(img1):', type(img1))
    print('img1.shape:', img1.shape)
    if len(img1.shape)==2:
        print('img1은 흑백(grayscale이다)')
    elif len(img1.shape)==3:
        print('img1은 컬러(truecolor)이다.')
    cv2.imshow('img1',img1.T)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [8]:
funct1()

type(img1): <class 'numpy.ndarray'>
img1.shape: (480, 640)
img1은 흑백(grayscale이다)


In [9]:
def func2():
    img1=np.empty((480,640),np.uint8)#흑백이미지
    img2=np.zeros((480,640,3),np.uint8)#컬러이미지   
    img3=np.ones((480,640),np.uint32)#1로 채워진 행렬
    img4=np.full((480,640),0,np.float32)#0로 채워진 행렬
    
    mat1=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]]).astype(np.uint8)
    
    mat1[0,1]=100
    mat1[2,:]=200
    print(img1)

In [10]:
func2()

[[ 80   1 202 ...  83  81  79]
 [  2   0   0 ...   1   0   0]
 [ 15   0   0 ...   1   0   0]
 ...
 [241 241 241 ... 164 163 161]
 [162 162 162 ... 165 167 168]
 [169 170 171 ...  10  10  10]]


In [11]:
def func3():
    img1=cv2.imread('images/cat.bmp')
    img2=img1 #주소복사, 같은 위치의 공간을 가리키고 있다.(얕은 복사/shallow)
    img3=img1.copy() #깊은 복사(deep copy)
    img1[:,:]=(255,0,0) #blue
    
    cv2.imshow('img1',img1)
    cv2.imshow('img2',img2)    
    cv2.imshow('img3',img3)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [12]:
func3()

In [13]:
def func4():
    img1=cv2.imread('images/lenna.bmp',cv2.IMREAD_GRAYSCALE)
    img2=img1[200:400,200:400].copy()
    img3=img1[200:400,200:400].copy()
    img2+=20
    print('shape: ' ,img1.shape, 'shape2',img2.shape)
    print('img',img1[200:400,200:400][0],'img2: ',img2[:,:][0],)
    cv2.imshow('img1',img1)
    cv2.imshow('img2',img2)
    cv2.imshow('img3',img3)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [14]:
func4()

shape:  (512, 512) shape2 (200, 200)
img [ 77  72  82  78  74  73  71  67  64  74  85  94  83  80  77  64  63  63
  57  49  50  61  92  99  74  44  39  36  38  39  43  60  61 101  72  97
 115  61  46  54  59  54  57  60  54  77 129  98  74  67  85 111 119  94
  83  69  44  38  50  76 125 133  81  31  32  39  70 143 159 177 174 137
 122 110 119 122 143 171 188 198 200 198 196 195 190 194 192 191 190 182
 180 181 179 176 181 181 179 184 181 174 179 185 179 181 179 177 173 177
 173 180 177 175 174 176 176 182 181 190 194 187 186 192 195 195 192 187
 194 188 191 195 198 192 193 186 169 128  88  55  48  46  46  57  95 108
 114 104  76  61  96 133 147 136 112 105 123 133 116 111 128 138 147 154
 147 151 153 169 166 173 170 170 174 172 174 179 181 178 187 195 200 206
 191 153  97  57  45  37  38  40  42  41  42  47  46  48  47  51  53  51
  51  50] img2:  [ 97  92 102  98  94  93  91  87  84  94 105 114 103 100  97  84  83  83
  77  69  70  81 112 119  94  64  59  56  58  59  63  80  81 121  

In [15]:
def func5():
    mat1=np.array(np.arange(12)).reshape(3,4)
    print('mat: ')
    print(mat1)
    h, w = mat1.shape[:2]
    mat2=np.zeros(mat1.shape, type(mat1))
    for j in range(h):
        for i in range(w):
            mat2[j,i]=mat1[j,i]+10
    print('mat2:')
    print(mat2)

In [16]:
func5()

mat: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat2:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [17]:
def func6():
    mat1=np.zeros((3,4),np.int32)
    mat2=np.arange(12).reshape(3,4)
    mat3=mat1+mat2
    mat4=mat2*2
    print("mat1: ",mat1,sep="\n")
    print("mat2: ",mat2,sep="\n")    
    print("mat3: ",mat3,sep="\n")    
    print("mat4: ",mat4,sep="\n")    

In [18]:
func6()

mat1: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
mat2: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat3: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
mat4: 
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [21]:
#문제 5)img1의 이미지의 밝기가 70~150(중간 밝기) 사이 인것을
#img1의 이미지의 밝기를 255(흰색)로 변경함
def func9():
    img1=cv2.imread('images/lenna.bmp')
    avg=((img1[:,:,1]+img1[:,:,0]+img1[:,:,2])/3.0) #BGR 평균
    avg_int=avg.astype(np.uint8)
    #실수를 정수로 변환
    boolean_arr = (avg_int[:,:]>75)&(avg_int[:,:]<=80)  #픽셀값이 75~200사이
    avg[boolean_arr]=240 #해당 index의 값을 바꿈
    cv2.imshow('avg_int',avg_int)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [22]:
func9()

In [25]:
def func4_1():
    img1=cv2.imread('images/lenna.bmp',cv2.IMREAD_GRAYSCALE)
    img2=img1[:,:].copy()
    mask=(img2>=70)&(img2<=150)
    img2[mask]=(50)
    cv2.imshow('img1',img1)
    cv2.waitKey()
    cv2.destroyAllWindows()
    
func4_1()

In [ ]:
def func7():
    img1=cv2.imread('images/lenna.bmp')
    avg=((img1[:,:,1]+img1[:,:,0]+img1[:,:,2])/3.0).astype(np.int64) #0bleu,1green,2red
    new_bgr=np.zeros((512,512,3),np.int64)
    for idx_i,i in enumerate(avg):
        for idx_j,j in enumerate(i):
            if j>=70 and j<150:
                new_bgr[idx_i,idx_j]=[0,0,255]
            else:
                new_bgr[idx_i, idx_j] = [j, j, j]
#     print(avg.shape)
#     print(new_bgr.shape)
    return new_bgr


In [ ]:
import cv2
import numpy as np

def func7():
    img1 = cv2.imread('images/lenna.bmp')
    avg = ((img1[:,:,1] + img1[:,:,0] + img1[:,:,2]) / 3.0).astype(np.int64)  # 0: blue, 1: green, 2: red
    new_bgr = np.zeros((512, 512, 3), np.uint8)  # Create a new BGR image array
    
    for idx_i, i in enumerate(avg):
        for idx_j, j in enumerate(i):
            if j >= 70 and j < 150:
                new_bgr[idx_i, idx_j] = [0, 0, 255]  # Set red color (BGR format) for pixels within the specified range
            else:
                new_bgr[idx_i, idx_j] = [j, j, j]  # Set grayscale color for other pixels
    
    return new_bgr

# 이미지 생성 및 저장
new_image = func7()
cv2.imwrite('images/new_image.jpg', new_image)


In [ ]:
#문제6 img1의 이미지의 크기에서 중간 영역(좌표 200:300,200:400)의 밝기를 0으로 설정함