In [3]:
import sympy as sp

$$ x+2y+3z=2 $$
$$ 2x+2y+2z=4 $$
$$ 3x+6y+7z=8 $$

\begin{bmatrix}
1\\
 2\\
3
\end{bmatrix}
\begin{bmatrix}
1\\
 2\\
6
\end{bmatrix}
\begin{bmatrix}
1 \\
 2\\
7
\end{bmatrix}

In [17]:
import numpy as np

In [54]:
a = np.array([1,2,3])
b = np.array([1,4,6])
c = np.array([1,2,7])

In [67]:
a = np.array([1,1,1])
b = np.array([2,4,2])
c = np.array([3,6,7])

In [69]:
A=[a,b,c]
print(A)
np.linalg.inv(A)

[array([1, 1, 1]), array([2, 4, 2]), array([3, 6, 7])]


array([[ 2.00000000e+00, -1.25000000e-01, -2.50000000e-01],
       [-1.00000000e+00,  5.00000000e-01, -0.00000000e+00],
       [-8.32667268e-17, -3.75000000e-01,  2.50000000e-01]])

In [70]:
d=np.array([2,4,100])

In [71]:
np.dot(np.linalg.inv(A),d)

array([-2.15000000e+01, -2.22044605e-16,  2.35000000e+01])

In [74]:
b*-35.75+c*24.5

array([  2.,   4., 100.])

In [22]:
a*1.5+b*0+c*0.5

array([2., 4., 8.])

In [20]:
4*b-3*c

array([1, 2, 3])

In [4]:
x,y,z= sp.symbols('x y z')

In [28]:
eq1=sp.Eq(x+y+z,2)
eq2=sp.Eq(2*x+3*y+2*z,4)
eq3=sp.Eq(3*x+6*y+7*z,100)

In [29]:
sp.solve([eq1,eq2,eq3])

{x: -43/2, y: 0, z: 47/2}